name: Build and Deploy
on:
  push:
    branches: [master]  # Changed from 'main' to 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            your-dockerhub-username/your-image:latest
            your-dockerhub-username/your-image:${{ github.sha }}

  deploy-to-render:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: render-actions/deploy@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceId: your-render-service-id
